spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 854897544350-rms8o1uo7m9moe59e9frofljef1i6m2h.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          kakao:
            client-id: 38b80be01bd3beb1ee86c5ace89487ba
            client-secret: lUkqoKS4fMMHNQyChsdOZB9pnkFvZqCw
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
            client-name: Kakao
          naver:
            client-id: HGLwkR9r1pTAH6Ied4C1
            client-secret: KDHH0kJFKZ
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver
        provider:
          google:
            user-name-attribute: sub
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
