spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 854897544350-rms8o1uo7m9moe59e9frofljef1i6m2h.apps.googleusercontent.com
            client-secret: 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
          kakao:
            client-id: 38b80be01bd3beb1ee86c5ace89487ba
            client-secret: lUkqoKS4fMMHNQyChsdOZB9pnkFvZqCw
          naver:
            client-id: HGLwkR9r1pTAH6Ied4C1
            client-secret: KDHH0kJFKZ