name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gradle wrapper present?
        run: test -f gradlew && echo "gradlew exists" || (echo "no gradlew" && exit 1)
      - name: Ping
        run: echo "CI skeleton ready"